import { readable, writable } from "svelte/store"

export let dles = writable([])
export let filteredDles = writable([])
export let tagNames = writable([])
export let tags = writable({})
export let filtersContainerHeight = readable(110)
export let numColumns = writable(2)
export let toolbarSelection = writable("")
export let settings = writable({})
export let categories = writable([])
export let categoryColors = writable({})
export let randomCategories = writable([])
export let infoHidden = writable(false)
export let favorites = writable([])
export let poppedUpDle = writable("")